services:
  - type: web
    name: ah6-cricket-backend
    env: node
    region: singapore
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: SCORER_EMAIL
        value: scorer@ah6cricket.com
      - key: SCORER_PASSWORD
        value: AH6Cricket@2026
      - key: FRONTEND_URLS
        value: "*"
      - key: DATABASE_URL
        fromDatabase:
          name: ah6-cricket-db
          property: connectionString

databases:
  - name: ah6-cricket-db
    databaseName: ah6cricket
    user: ah6admin
    plan: free
    region: singapore
